name: Testing pipeline
on: [push, pull_request]
jobs:

  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
             sudo apt-get -qq update
             sudo apt-get -y -qq dist-upgrade
             sudo apt-get -y -qq install gcc g++ cmake autoconf git
      - name: Tests
        run: |
             mkdir spider_build
             cd spider_build
             cmake ../tests
             cmake --build .
             ./tests --gtest_output="xml:report.xml"
             
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
             sudo apt-get -qq update
             sudo apt-get -y -qq dist-upgrade
             sudo apt-get -y -qq install gcc g++ cmake autoconf clang clang-tidy clang-format
      - name: Run linting
        run: |
             cd libSearchSECOSpider
             clang-tidy *.cpp --extra-arg=-std=c++20 --
             clang *.cpp -fsyntax-only -std=c++20